### PR TITLE
Include artists in search

### PR DESCRIPTION
**Pull request by bendardenne**
Issue #12 

A separate request is made to the Artists endpoint. 

If I have some time later I might revamp the search view to present artists, albums and songs separately.

### CODE REVIEW

**Comment by dkanada** [comment]
It looks like you changed the sort method, any chance you could make that a configurable setting somewhere? I like the artists and albums at the top because it's what I need 90% of the time.

**Comment by dkanada** [comment]
I'd also be fine with search page changes if something like the now playing setting was implemented where users could switch between them.

**Comment by bendardenne** [comment]
> It looks like you changed the sort method, any chance you could make that a configurable setting somewhere? I like the artists and albums at the top because it's what I need 90% of the time.

That's what the current comparator does :) At least it should, if it doesn't, then it's a bug. 

Previously it would put artists and albums at the top, but it wouldn't differentiate, so you would have artists and albums intertwined. I just separated artists first, then albums. Then within each category, it's sorted alphabetically, whereas previously it was random. 

I'm fine with a setting, but what other sort methods do we want? I also usually want artist / album / tracks.

**Comment by dkanada** [comment]
Ah, I wasn't looking closely enough! I'll get this merged for the next release.

**Pull request merged**
