### PR TITLE
Replace QueueStore SQL with json save/load in PreferenceUtil

### PR DESCRIPTION
**Pull request by rotvel**
The song details dialog you added is nice, but it crashes Gelli if you try to view details on a song in the queue that has been loaded at Gelli startup.

This is because the queue sql only saves a subset of the of the properties of each Song and we get a npe when accessing one of them. 

Fixing this lead to ripping out the entire sql queue storage and replacing it with a simple json save/load mechanism in PreferenceUtil. Let me know what you think.  I'm marking it as draft because it probably needs some cleanup, but the queue save/load works.

### CODE REVIEW

**Comment by rotvel** [comment]
I don't know why one of your commits crept in here :)

**Comment by dkanada** [comment]
It might be a better idea to rewrite the QueueStore, because if we ever want full offline support, using SQL is probably more efficient than a JSON store. Although it's just a suggestion, because I obviously haven't written any of the other requirements for offline support yet haha.

**Comment by dkanada** [comment]
I wonder if we should bother storing this information or just always fetch it when requested...I always wonder what the proper amount of caching should be, it always complicates things. The bitrate and such would definitely be useful for local downloads, but you could probably just query the file.

**Comment by dkanada** [comment]
I finished the database migration so this pull request is unfortunately deprecated. It only includes the songs required for the queue at this point but I tried to design it to eventually store whatever Gelli needs to work offline. I'm still completely undecided on whether I want to support API calls *and* database calls throughout the app or if I should just emulate the Kodi client and rely completely on the database.

**Pull request closed without merging**
