### PR TITLE
Detect battery optimization on startup

### PR DESCRIPTION
**Pull request by CappielloAntonio**
Check if battery optimizations is enabled or not on startup. 
If optimizations are enabled a dialog took the user to battery optimizations settings.

Nota bene: the app itself do not ignore optimization settings but ask the user if he want to change them, so it shouldn't be a problem to eventually publish the app on the PlayStore.

### CODE REVIEW

**Comment by KristupasSavickas** [comment]
Is this really an issue? I thought media players have an exempt from battery saving while playing.

**Comment by dkanada** [comment]
It can definitely be an issue. I'm actually going through the codebase though, and it seems like this should go in `AbsBaseActivity` instead of the splash activity. I wonder what else I should have moved to that activity. It seems like moving some of the API client initialization stuff to `onResume` over there might fix the related crashes.

**Comment by dkanada** [comment]
Regardless, the BaseActivity refactor can come later, this seems like a net benefit so I'll merge this pull request first.

**Comment by CappielloAntonio** [comment]
> @CappielloAntonio have you noticed issues even with the battery optimizations disabled? I seem to have run into infinite repeats a few times when the wakelock wasn't acquired during queue playback.

Honestly i didn't notice any improvements, not with LineageOS. But maybe checking battery optimization could help with phones who aggressively try to "optimize" power consumption (some chinese phone manufacter with their custom features like in MIUI, ColorOS, EMUI and so on).

**Pull request merged**
