### PR TITLE
Add a favorites tab

### PR DESCRIPTION
**Pull request by luuknieuwdorp**
Threw this together pretty quickly because I wanted an easy way to view al my favorited tracks. This PR adds a FavoritesFragment based on the already existing SongsFragment. Related to #37.

Here's an APK of a personal build if anyone wants to test it.
[app-debug.zip](https://github.com/dkanada/gelli/files/5782696/app-debug.zip)

### CODE REVIEW

**Comment by digitalentity** [comment]
Just tested. Works perfectly, thanks a lot! @dkanada can we have this merged please, this is super useful?

**Comment by dkanada** [comment]
Rather than a separate tab, I was hoping to add a new item to the context menu to filter by certain properties on any tab, including favorites and watch status. Since all items can be favorited it would be much more inclusive than a songs-only favorites tab.

**Comment by luuknieuwdorp** [comment]
I think a better solution might be to have both, as it's quite imaginable that a user might f.e. want to have a list of all their recently added songs to their library, and an easy way to view favorites instead, without juggling filtering options every time.

I suggest adding the filtering options and keeping the separate favorites tab, possibly disabling it by default and turning it in to an *actual* favorites tab with hearts next to the songs like most other streaming services.
Screenshot_20210108-142641_Spotify

**Comment by digitalentity** [comment]
I also think a separate Favourites tab (possibly **in addition** to filters) would be better. This will align the UI/UX better with other streaming services (which will in turn improve the UX for users migrating from i.e. Spotify or YTM)

**Comment by neopc10** [comment]
As somebody who hates "favorites," keeping these hearts out of my view/queue by default would be appreciated.

**Comment by dkanada** [comment]
With your latest commit the code additions are so minimal I'm fine adding this in the next release. Unfortunately, it's currently blocked because when the app is first opened, only a single song in the restored queue will play even when more items exist, so there's a bug with the `PLAY_NEXT` event to resolve first.

**Comment by luuknieuwdorp** [comment]
I suspected something might've been up but hadn't had time to test if it was due to my code changes yet. I'll take a look at it when I have time.

**Comment by dkanada** [comment]
My best guess is either `MusicService.java` or `MultiPlayer.java` but I'm leaning towards the former. The `PREPARE_NEXT` constant is almost certainly what to look into, because it's responsible for queuing new items. Sorry I didn't see your edit, GitHub doesn't notify without a new comment.

**Comment by dkanada** [comment]
I've spent more time than I'd care to admit trying to figure out the best way to remove that constant without adding too much code but it really does make the ExoPlayer portion much easier to deal with. It will almost certainly need to get thrown out before I add Chromecast or Session support though.

**Comment by luuknieuwdorp** [comment]
@dkanada
Seeing that you merged it, I take it the bug was unrelated to the my code changes? I'm also having trouble reproducing it locally, though it does appear sometimes seemingly randomly after the app is closed and started up again, but not other times.

**Comment by dkanada** [comment]
Correct, it's unrelated. I was just commenting on the release status since people were requesting this get pushed quickly.

**Comment by dkanada** [comment]
I found the issue, I'll push an update soon.

**Pull request merged**
