### PR TITLE
Remove UnknownMediaSourceFactory

### PR DESCRIPTION
**Pull request by jakobkukla**
This removes UnknownMediaSourceFactory and infers if the server is transcoding based on Codec, Container and MaxBitrate settings. 

I haven't tested this yet with more exotic codecs and containers. Since this relies on the codec list in PreferenceUtil we should think about expanding / adjusting it.

### CODE REVIEW

**Comment by jakobkukla** [comment]
**About supported containers:**
From https://exoplayer.dev/supported-formats.html#progressive-container-formats

| Container format | Comments |
| ---| ---| 
| MP4 |  |
| M4A |  |
| FMP4 |  |
| WebM |  |
| Matroska |  |
| MP3 | Some streams only seekable using constant bitrate seeking |
| Ogg | Containing Vorbis, Opus and FLAC |
| WAV |  |
| MPEG-TS |  |
| MPEG-PS | |
| FLV| Not seekable |
| ADTS (AAC) | Only seekable using constant bitrate seeking |
| FLAC |  |
| AMR |  Only seekable using constant bitrate seeking|
| JPEG motion photo | Only the MP4 content is extracted |

I suggest we transcode the formats which are not seekable and some of the more obscure formats (FLV, JPEG, AMR?). Since Codecs don't really seem to matter (except for Ogg which only supports Vorbis, Opus and FLAC), we should probably just check if the Container is supported (except for Ogg).

We should also decide if we want to enable constant bitrate seeking (for ADTS and AMR (and some MP3s)) or just transcode these formats.

**Comment by dkanada** [comment]
After some initial testing I noticed this will break if the server administrator disables audio transcoding. Perhaps rather than remove UnknownMediaSource we should just include a SmartMediaSource that includes and a setting to switch between them. The default would be your new logic, but we would keep the server check logic for full compatibility.

**Comment by dkanada** [comment]
After some initial testing I noticed this will break if the admin disables audio transcoding. Perhaps rather than remove UnknownMediaSource we should just include a SmartMediaSource and a setting to switch between them. The default would be your new logic, but we would keep the server check for full compatibility.

**Comment by jakobkukla** [comment]
How about using MediaSourceInfo's supportsTranscoding property? I haven't had time to look into it yet but I assume it will reflect the server-wide transcoding setting. 

> Perhaps rather than remove UnknownMediaSource we should just include a SmartMediaSource and a setting to switch between them. The default would be your new logic, but we would keep the server check for full compatibility.

Sure we could keep the old logic but I'd rather not have that one http request slow things down. imo things should just work with the default logic. I just need to get the PR to that point :smile:

**Pull request merged**
